name: Marks sync (Bakaláři ⇄ Živý obraz)

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: marks-sync
      cancel-in-progress: false
    timeout-minutes: 3

    env:
      BAKALARI_BASE_URL: ${{ secrets.BAKALARI_BASE_URL }}
      BAKALARI_USERNAME: ${{ secrets.BAKALARI_USERNAME }}
      BAKALARI_PASSWORD: ${{ secrets.BAKALARI_PASSWORD }}
      IMPORT_KEY: ${{ secrets.ZIVY_OBRAZ_IMPORT_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies (if any)
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      - name: Run marks-sync
        run: |
          node src/marks-sync.mjs
