name: Traffic sync (Golemio ⇄ Živý obraz)

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: traffic-sync
      cancel-in-progress: false
    timeout-minutes: 3

    env:
      DEPARTURE_PREFIX: ''

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies (if any)
        run: |
          if [ -f package.json ]; then
            npm ci
          fi

      - name: Run traffic-sync
        run: |
          ARGS=(
            --stop-id="${{ secrets.GOLEMIO_STOP_ID }}"
            --import-key="${{ secrets.ZIVY_OBRAZ_IMPORT_KEY }}"
            --golemio-token="${{ secrets.GOLEMIO_TOKEN }}"
          )
          if [ -n "${DEPARTURE_PREFIX}" ]; then
            ARGS+=(--departure-prefix="${DEPARTURE_PREFIX}")
          fi
          node src/traffic-sync.mjs "${ARGS[@]}"
